# Generated by Django 3.0 on 2022-05-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0007_auto_20220512_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t',
        ),
    ]
