version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build_and_test:
    working_directory: ~/app
    docker:
      - image: python:3.8-slim-buster
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install -r requirements.txt
      - run:
          name : run app
          working_directory: ~/app/oc_lettings_site
          command: |
            python -m pytest
            python -m flake8

#  test:
#    working_directory: ~/app
#    docker:
#      - image: python:3.8-slim-buster
#    steps:
#      - checkout
#      - python/install-packages:
#          pkg-manager: pip
#      - run: pip install -r requirements.txt
#      - run:
#          working_directory: ~/app/oc_lettings_site
#          command: python -m pytest
#      - run:
#          name : Linting
#          command: flake8
#  deploy:
#    working_directory: ~/app
#      docker:
#        - image: python:3.8-slim-buster
#      steps:
#        - checkout
#    docker build -t app_oc_lettings_site:1 .
#    docker login -u $DOCKER_USER -p $DOCKER_PASS
#    docker tag julienx2/app_oc_lettings_site:1 julienx2/app_oc_lettings_site:1
#    docker push julienx2/app_oc_lettings_site:1


workflows:
  master_workflows:
    jobs:
      - build_and_test
#      - test:
#          requires:
#            - build
