version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.8-slim-buster
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          path: oc_lettigns_site/
          command: |
            pip install -r requirements.txt
            python manage.py runserver

workflows:
  build:
    jobs:
      - build
