version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build_and_test:
    working_directory: ~/app
    docker:
      - image: python:3.8-slim-buster
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install -r requirements.txt
      - run:
          name : run tests
          working_directory: ~/app/oc_lettings_site
          command: |
            python -m pytest
            python -m flake8

  build_and_deploy:
    working_directory: ~/app
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: push dockerhub
          command: |
            TAG=${CIRCLE_SHA1}
            docker build -t julienx2/app_oc_lettings_site:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag julienx2/app_oc_lettings_site:$TAG julienx2/app_oc_lettings_site:latest
            docker push julienx2/app_oc_lettings_site:$TAG
            docker push julienx2/app_oc_lettings_site:latest

  deploy_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy image Docker to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login




workflows:
  workflows_master:
    jobs:
      - build_and_test
      - build_and_deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build_and_test
      - deploy_heroku

