version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.8-slim-buster
    steps:
      - checkout
      - run: python3 manage.py runserver

workflows:
  build_and_test:
    jobs:
      - build