version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.8-slim-buster
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pip install -r requirements.txt
      - run:
          command: |
            oc_lettigns_site/ python manage.py runserver

workflows:
  build:
    jobs:
      - build
