# Generated by Django 3.0 on 2022-05-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0004_auto_20220512_1313'),
        ('oc_lettings_site', '0002_auto_20220512_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='letting',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lettings.Address'),
        ),
    ]
