# Generated by Django 3.0 on 2022-05-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20220512_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letting',
        ),
    ]
