# Generated by Django 3.0 on 2022-05-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_address'),
    ]

    operations = [migrations.RunSQL("""
                INSERT INTO lettings_address (
                    id,
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
                )
                SELECT
                    id,
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
                FROM
                    oc_lettings_site_address;
            """, reverse_sql="""
                INSERT INTO oc_lettings_site_address (
                    id,
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
                )
                SELECT
                    id,
                    number,
                    street,
                    city,
                    state,
                    zip_code,
                    country_iso_code
                FROM
                    lettings_address;
            """)
        
    ]
