# Generated by Django 3.0 on 2022-05-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20220512_1306'),
    ]

    operations = [
        migrations.RunSQL("""
        UPDATE `sqlite_sequence`
        SET `seq` = (SELECT MAX(`id`) FROM 'profiles_profile')
        WHERE `name` = 'profiles_profile';
        """)
    ]
