# Generated by Django 3.0 on 2022-05-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0005_letting'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE `sqlite_sequence`
            SET `seq` = (SELECT MAX(`id`) FROM 'lettings_letting')
            WHERE `name` = 'lettings_letting';
            """)
    ]
