# Generated by Django 3.0 on 2022-05-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0008_delete_t'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
